// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgryodpznkvvwuvsyvbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxncnlvZHB6bmt2dnd1dnN5dmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTU1MzYsImV4cCI6MjA2MDAzMTUzNn0.8PdTYm3gY6j9ss0T_a3H7V_8Lo1iBQYFG36nr5xXB3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);